### ISSUE TITLE
Conflict with rautomation 0.6.3 and 0.7.0 (win32screenshot v 1.0.7)

### ISSUE THREAD

**Issue by enroxorz** [jarmo/win32screenshot#14]
WATIR 2.0.4 requires rautomation 0.6.3 (which I cannot uninstall)
With the new rautomation 0.7.0 requirement in the gemspec a conflict is created. (see stacktrace Set 1 below)
Tried to remove rautomation 0.6.3, but the WATIR dependency screwed things up. (see stacktrace Set 2)

Had to revert to win32screenshot 1.0.6 for now

Ruby 1.87 on Win XP

SET 1

Unable to activate win32screenshot-1.0.7, because rautomation-0.6.3 conflicts wi
th rautomation (~> 0.7.0) (Gem::LoadError)
C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/specification.rb:1626:in `raise_if_co
nflicts'
C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/specification.rb:741:in `activate'
C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems.rb:211:in `try_activate'
C:/Ruby187/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:59:in `require'
C:/lcpic/singlerun/features/step_definition/definition.rb:4
C:/Ruby187/lib/ruby/gems/1.8/gems/cucumber-1.1.9/bin/../lib/cucumber/rb_support/
rb_language.rb:129:in `load'
C:/Ruby187/lib/ruby/gems/1.8/gems/cucumber-1.1.9/bin/../lib/cucumber/rb_support/
rb_language.rb:129:in `load_code_file'
C:/Ruby187/lib/ruby/gems/1.8/gems/cucumber-1.1.9/bin/../lib/cucumber/runtime/sup
port_code.rb:171:in `load_file'
C:/Ruby187/lib/ruby/gems/1.8/gems/cucumber-1.1.9/bin/../lib/cucumber/runtime/sup
port_code.rb:83:in `load_files!'
C:/Ruby187/lib/ruby/gems/1.8/gems/cucumber-1.1.9/bin/../lib/cucumber/runtime/sup
port_code.rb:82:in `each'
C:/Ruby187/lib/ruby/gems/1.8/gems/cucumber-1.1.9/bin/../lib/cucumber/runtime/sup
port_code.rb:82:in `load_files!'
C:/Ruby187/lib/ruby/gems/1.8/gems/cucumber-1.1.9/bin/../lib/cucumber/runtime.rb:
175:in `load_step_definitions'
C:/Ruby187/lib/ruby/gems/1.8/gems/cucumber-1.1.9/bin/../lib/cucumber/runtime.rb:
40:in `run!'
C:/Ruby187/lib/ruby/gems/1.8/gems/cucumber-1.1.9/bin/../lib/cucumber/cli/main.rb
:43:in `execute!'
C:/Ruby187/lib/ruby/gems/1.8/gems/cucumber-1.1.9/bin/../lib/cucumber/cli/main.rb
:20:in `execute'
C:/Ruby187/lib/ruby/gems/1.8/gems/cucumber-1.1.9/bin/cucumber:14
C:/Ruby187/bin/cucumber:19:in `load'
C:/Ruby187/bin/cucumber:19

SET 2

The system cannot find the file specified. (Win32::Registry::Error)
C:/Ruby187/lib/ruby/1.8/win32/registry.rb:528:in `open'
C:/Ruby187/lib/ruby/1.8/win32/registry.rb:608:in `open'
C:/Ruby187/lib/ruby/gems/1.8/gems/firewatir-1.9.4/lib/firewatir/firefox.rb:964:in `path_from_registry'
C:/Ruby187/lib/ruby/gems/1.8/gems/firewatir-1.9.4/lib/firewatir/firefox.rb:934:in `path_to_bin'
C:/Ruby187/lib/ruby/gems/1.8/gems/firewatir-1.9.4/lib/firewatir/firefox.rb:64:in `launch_browser'
C:/Ruby187/lib/ruby/gems/1.8/gems/firewatir-1.9.4/lib/firewatir/firefox.rb:40:in `initialize'
C:/Ruby187/lib/ruby/gems/1.8/gems/commonwatir-2.0.4/lib/watir/browser.rb:65:in `new'
C:/Ruby187/lib/ruby/gems/1.8/gems/commonwatir-2.0.4/lib/watir/browser.rb:65:in `new'
C:/lcpic/singlerun/features/step_definition/definition.rb:13:in `Before'

**Comment by jarmo** [comment]
I'm not sure if this is a problem anymore since it is really old issue. Please create a new issue if problem still exists. Closing this.
