### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by lhoff** [jarmo/win32screenshot#17]
Hello. I'm having issues installing this gem. (I'm also new to Ruby, so bear with me.)

When I run 
  gem install win32screenshot

I get
ERROR:  While executing gem ... (Errno::EINVAL)
    Invalid argument - C:/Ruby187/lib/ruby/gems/1.8/gems/mini_magick-3.6.0/test/files/special! "chars'.gif

What does this mean?

Thanks!

**Comment by jarmo** [comment]
Use newer Ruby and there should not be any problems nowadays. Closing this old issue.
