### ISSUE TITLE
Install 1.0.10 tries to install ffi 1.9.0 when ffi 1.9.3 already installed.  ffi gem install fails

### ISSUE THREAD

**Issue by pmneve** [jarmo/win32screenshot#19]
It doesn't seem to see that ffi 1.9.3 is already there.
ruby 2.0.0p353 (2013-11-22) [x64-mingw32]
win 7 64 bit
64 bit devkit

C:\Users\awetestlib\Downloads>gem install win32screenshot
Fetching: ffi-1.9.0.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing win32screenshot:
        ERROR: Failed to build gem native extension.

    C:/Ruby200-x64/bin/ruby.exe extconf.rb
checking for ffi.h... no
checking for ffi.h in /usr/local/include,/usr/include/ffi... no
checking for rb_thread_blocking_region()... yes
checking for rb_thread_call_with_gvl()... yes
checking for rb_thread_call_without_gvl()... yes
checking for ffi_prep_cif_var()... no
creating extconf.h
creating Makefile

make "DESTDIR="
generating ffi_c-x64-mingw32.def
      0 [main] mkdir 5760 open_stackdumpfile: Dumping stack trace to mkdir.exe.stackdump
make: *** ["/c/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ffi-1.9.0/ext/ffi_c/libffi-x64-mingw32"/.libs/libffi_convenience.a] Error 5

Gem files will remain installed in C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ffi-1.9.0 for inspection.
Results logged to C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/ffi-1.9.0/ext/ffi_c/gem_make.out

**Comment by jarmo** [comment]
Closing this due to inactitivy.
