### ISSUE TITLE
ImageMagick Portable asking for MSVCP120.dll - upgrading to 6.9.2 resolves issues.

### ISSUE THREAD

**Issue by ryancastro** [jarmo/win32screenshot#22]
I'm using Win32Screenshot on several different Windows machines running 8, 8.1, and Window Server 2012 Data Center. I have several machines where convert.exe won't execute from the /ext/ directory of Win32Screenshot without errors. First it barked about a missing DLL (MSVCP120.dll), then it had a generic unknown error once I give it that DLL. I decided to drop the convert.exe from ImageMagick into it, and all of a sudden everything worked like a charm.

I don't know what specific dependency or OS is causing the issue - it works on about half our machines. Machines that come out of the box with a fresh install of windows and nothing else seem to struggle with running the Portable 6.9.1 that you packaged. However, 6.9.2 works great across all versions I've seen. 

I chose not to do a pull request because it looks like you've been selective about your file packaging and only using the bare necessity, so this is simply a request to bump up from ImageMagick Portal 6.9.1 to 6.9.2.  I got the working files here: http://www.imagemagick.org/script/binary-releases.php#windows

So, this is a request to bump up to 6.9.2 for better compatibility across windows.

**Comment by ryancastro** [comment]
Ugh. You can also install this package with 6.9.1:
https://www.microsoft.com/en-us/download/details.aspx?id=40784 And that should fix your issues, if the gem doesn't get upgraded to 6.9.2

I have no explanation as to why 6.9.1 needs that distributable package, but 6.9.2 doesn't. I'm sure it is a dependency change on ImageMagick's end, but it makes 6.9.1 a huge hassle for anyone deploying thin clients using this gem.

**Comment by jarmo** [comment]
I'd be willing to accept a pull request, becase I do not have time to do the whole process myself.

I guess I was selective because I didn't want the gem to be too big in file size, but maybe that's not that important. I'd say working installation is more important than file size.

**Comment by ryancastro** [comment]
I updated to ImageMagick-6.9.2-8-portable-Q16-x86 with success. I did a new pull request, but I guess git just merged it with my existing Pull request where I also added the `write!` method.

How is this looking to you? I did not update history.rdoc because I figured you'd do that just before pushing your gem.

**Comment by jarmo** [comment]
Closing this due to release.
