### ISSUE TITLE
LengthAndFilesizeDoNotMatch error when saving to PNG.

### ISSUE THREAD

**Issue by kapoorlakshya** [jarmo/win32screenshot#24]
I am using win32screenshot-2.1.0 through watir-classic-4.3.0 with Cucumber to capture some screenshots of an application in IE 11. This gem works fine with BMP images, but whenever I save to PNG or JPG I receive the following error message:

```
identify.exe: LengthAndFilesizeDoNotMatch `C:/Users/LAKSHY~1/AppData/Local/Temp/mini_magick20160926-10612-8akxxq' @ warning/bmp.c/ReadBMPImage/817.
convert.exe: LengthAndFilesizeDoNotMatch `C:/Users/LAKSHY~1/AppData/Local/Temp/mini_magick20160926-10612-8akxxq' @ warning/bmp.c/ReadBMPImage/817.
```

The image does save and looks like this: 

![_codedescription_fail](https://cloud.githubusercontent.com/assets/4314581/18853161/a55fa28a-83f8-11e6-9d10-58dc63d35983.png)

I am using mini_magick-4.3.6 as listed in the gemspec. Trying to figure out if this is a known issue or if you have a workaround for it. Thanks!

**Comment by jarmo** [comment]
Sorry, but I have not seen this error before. Does this happen on more than one computer? Is there anything special going on with that computer?

Can you also try directly using win32screenshot for taking different screenshots (see examples in [README](https://github.com/jarmo/win32screenshot/blob/master/README.rdoc))?

**Comment by kapoorlakshya** [comment]
Sorry for the delayed response.

It does happen when I directly use win32screenshot. I am on Windows 7 Professional x64, and it only happens on the Windows 7 machines. I tried it on a Windows 10 and Windows 8 machine and it does not happen there.

2 screenshots from different Windows 7 Pro x64 machines -- first is a physical machine and second is a VM:

![image](https://cloud.githubusercontent.com/assets/4314581/18967460/24457fbe-863a-11e6-83fb-96bff02df499.png)

![image2](https://cloud.githubusercontent.com/assets/4314581/18967521/5de519a0-863a-11e6-92c7-b5c4efe14768.png)

This is really strange...

**Comment by kapoorlakshya** [comment]
You can mark this as closed. Turns out it was an environment specific issue, possibly DLP policies.
