### ISSUE TITLE
Resize Image

### ISSUE THREAD

**Issue by QAsSpread** [jarmo/win32screenshot#25]
You can resize the image. To make it lighter

**Comment by jarmo** [comment]
?

**Comment by QAsSpread** [comment]
Yes, this is a question. :) Forgotten "?"

**Comment by jarmo** [comment]
If the original question was "Can you resize images with win32screenshot?" then the answer is no - this library only captures screenshots of specified windows/areas. You might want to use [minimagick](https://github.com/minimagick/minimagick) or something similar for resizing images after the fact.

For further questions, which are not issues per se, please use StackOverflow.

Closing this issue.
