### ISSUE TITLE
Comflict with ffi 

### ISSUE THREAD

**Issue by damulhan** [jarmo/win32screenshot#32]
I used ruby 2.6 (windows 10 x64). After bundle install, I found that win32screenshot complete with ffi 1.3. Even I could not install 1.11.0 

>
> Unable to activate win32screenshot-3.0.0, because ffi-1.13.0-x64-mingw32 conflicts with ffi (~> 1.11.0)
>

**Comment by jarmo** [comment]
Just released a version of 3.1.0 which has many dependencies updated. Maybe this problem does not exist anymore? Closing for now.
