### ISSUE TITLE
MiniMagick::Invalid exception when using a directory that contains a space

### ISSUE THREAD

**Issue by dougcaron** [jarmo/win32screenshot#8]
Using a directory that includes a space seems to throw a MiniMagick::Invalid exception.  The screenshot gets created, but an exception is thrown when the image is being verified.  If I use a directory that does not include a space then no exception is thrown.  I have included the exception report and the Ruby code I ran to create it.

<code>
    C:/ruby/1.8.6-p383/lib/ruby/gems/1.8/gems/mini_magick-3.2/lib/mini_magick.rb:357:in `run': Magick: unable to open image `C:/Test\': No such file or directory @ error/blob.c/OpenBlob/2584. (MiniMagick::Invalid)
    Magick: no decode delegate for this image format `C:/Test\' @ error/constitute.c/ReadImage/532.
    Magick: unable to open image `Directory/image3.png': No such file or directory @ error/blob.c/OpenBlob/2584.
    Magick: unable to open file `Directory/image3.png' @ error/png.c/ReadPNGImage/3084.
        from C:/ruby/1.8.6-p383/lib/ruby/gems/1.8/gems/mini_magick-3.2/lib/mini_magick.rb:343:in `run_command'
        from C:/ruby/1.8.6-p383/lib/ruby/gems/1.8/gems/mini_magick-3.2/lib/mini_magick.rb:262:in `write'
        from C:/ruby/1.8.6-p383/lib/ruby/gems/1.8/gems/win32screenshot-1.0.2/lib/win32/screenshot/image.rb:38:in `write'
        from C:/dev/Workspaces/Scheduled Controls/lib/scheduled_control_class.rb:250
</code>

Here is the Ruby code (v1.8.6) I ran to create the exception:
<pre><code>
    require "rubygems"
    require "win32/screenshot"
    require "fileutils.rb"

    Win32::Screenshot::Take.of(:foreground).write("C:/Test Directory/image3.png")
</code></pre>

**Comment by jarmo** [comment]
This problem probably doesn't exist anymore. Closing.
